<?php

/**
 * Implements hook_menu().
 */
function achat_db_menu() {
  $items['achat_db/%centity/ajax/export'] = array(
    'page callback' => 'achat_db_ajax_export_callback',
    'page arguments' => array(1),
    'access arguments' => array('administer achat db'),
    'file' => 'achat_db.export.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function achat_db_permission() {
  return array(
    'administer achat db' => array(
      'title' => t('Administer achat database info.'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function achat_db_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'achat_db') . '/views',
  );
}

/**
 * Implements hook_achat_block_configure_alter().
 *
 * @see achat_block_configure()
 */
function achat_db_achat_block_configure_alter(&$form, $type, $blocks_settings) {
	$default_settings = _achat_block_default_configure();
  $form['achat']['db'] = array(
    '#type' => 'fieldset',
    '#title' => t('数据库'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );
  $form['achat']['db']['achat'] = array(
    '#type' => 'checkbox',
    '#title' => t('存储聊天室'),
    '#default_value' => isset($blocks_settings[$type]['db']['achat']) ? $blocks_settings[$type]['db']['achat'] : $default_settings['db']['achat'],
  );
  $form['achat']['db']['achatlog'] = array(
    '#type' => 'checkbox',
    '#title' => t('存储聊天记录'),
    '#default_value' => isset($blocks_settings[$type]['db']['achatlog']) ? $blocks_settings[$type]['db']['achatlog'] : $default_settings['db']['achatlog'],
    '#states' => array(
      'visible' => array(
        'input[name="achat[db][achat]"]' => array('checked' => TRUE),
      ),
    ),
  );
  $form['achat']['db']['history'] = array(
    '#type' => 'checkbox',
    '#title' => t('查看聊天记录'),
    '#default_value' => isset($blocks_settings[$type]['db']['history']) ? $blocks_settings[$type]['db']['history'] : $default_settings['db']['history'],
    '#states' => array(
      'visible' => array(
        'input[name="achat[db][achatlog]"]' => array('checked' => TRUE),
      ),
    ),
  );
}

/**
 * Implements hook_achat_block_save_alter().
 *
 * @see achat_block_save()
 */
function achat_db_achat_block_save_alter(&$settings, $edit) {
	$settings['db'] = array(
		'achat' => $edit['achat']['db']['achat'],
		'achatlog' => $edit['achat']['db']['achat'] && $edit['achat']['db']['achatlog'] ? 1 : 0,
		'history' => $edit['achat']['db']['achat'] && $edit['achat']['db']['achatlog'] && $edit['achat']['db']['history'] ? 1 : 0,
	);
}

/**
 * Implements hook_achat_block_default_configure_alter().
 *
 * @see achat_block_default_configure()
 */
function achat_db_achat_block_default_configure_alter(&$configure) {
	$configure['db'] = array(
		'achat' => 0,
		'achatlog' => 0,
		'history' => 0,
	);
}

/**
 * Implements hook_achat_create_socket_alter().
 *
 * @see achat_create_socket()
 */
function achat_db_achat_create_socket_alter($type, $channel) {
	$blocks_settings = achat_settings('blocks');
	if (isset($blocks_settings[$type]['db']['achat']) && $blocks_settings[$type]['db']['achat']) {
		if ($achat = achat_db_load_achat_by_channel($channel)) {
	  	// exist
	  	$wrapper = entity_metadata_wrapper('centity', $achat);
	  	$enter_user_ids = array();
	  	foreach ($wrapper->field_achat_enter_users->value() as $user) {
	  		$enter_user_ids[] = $user->uid;
	  	}
	  	if (!in_array($GLOBALS['user']->uid, $enter_user_ids)) {
		  	array_push($enter_user_ids, $GLOBALS['user']->uid);
		  	array_unique($enter_user_ids);
		  	$wrapper->field_achat_enter_users->set($enter_user_ids);
		  	$wrapper->save();
	  	}
		} else {
	  	// not exist, to create
	  	achat_db_create_achat($channel);
		}
	}
}

/**
 * Create achat.
 */
function achat_db_create_achat($channel) {
	$settings = array();
	$achat = centity_create(array('type' => 'achat'));
	$wrapper = entity_metadata_wrapper('centity', $achat);
	$wrapper->field_achat_channel->set($channel);
	$wrapper->field_achat_created->set(time());
	$wrapper->field_achat_enter_users->set(array($GLOBALS['user']->uid));
	drupal_alter('achat_db_create_achat', $achat, $wrapper, $channel);
	$wrapper->save();
}

/**
 * Load achat.
 *
 * @param $channel
 */
function achat_db_load_achat_by_channel($channel) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'centity')
    ->entityCondition('bundle', 'achat')
    ->fieldCondition('field_achat_channel', 'value', $channel)
    ->propertyOrderBy('cid', 'ASC')
    ->range(0, 1);
  $result = $query->execute();
  if (isset($result['centity'])) {
  	$cid = key($result['centity']);
  	return centity_load($cid);
  }
  return FALSE;
}

/**
 * Implements hook_achat_block_view_alter().
 *
 * @see achat_block_view()
 */
function achat_db_achat_block_view_alter($type, $channel, &$access, &$output) {
	if ($achat = achat_db_load_achat_by_channel($channel)) {
		$wrapper = entity_metadata_wrapper('centity', $achat);
		if ($wrapper->field_achat_limit->value() == 1) {
			$allow_user_ids = array();
	  	foreach ($wrapper->field_achat_allow_users->value() as $user) {
	  		$allow_user_ids[] = $user->uid;
	  	}
	  	$access = in_array($GLOBALS['user']->uid, $allow_user_ids);
	  	$output = t('Cloesed');
		}
	}
}

/**
 * Implements hook_achat_send_message_alter().
 *
 * @see achat_send_message()
 */
function achat_db_achat_send_message_alter($params) {
	if (isset($params['block_type'])) {
		$configure = _achat_block_configure($params['block_type']);
		if (isset($configure['db']['achatlog']) && $configure['db']['achatlog']) {
			if (isset($params['channel']) && $achat = achat_db_load_achat_by_channel($params['channel'])) {
				achat_db_create_achatlog($achat, $params);
			} else {
				watchdog('achat_db', 'Create achat log fail, invalid channel %channel', array('%channel' => $channel), WATCHDOG_ERROR);
			}
		}
	}
}

/**
 * Create achat log.
 *
 * @param $achat
 *
 * @param $params
 */
function achat_db_create_achatlog($achat, $params) {
	$settings = array();
	$achatlog = centity_create(array('type' => 'achatlog'));
	$wrapper = entity_metadata_wrapper('centity', $achatlog);
	$wrapper->field_achat->set($achat->cid);
	$wrapper->field_achatlog_sender->set($GLOBALS['user']->uid);
	if (isset($params['secret'])) {
		$wrapper->field_achatlog_secret->set(intval($params['secret']));
	}
	if (isset($params['to'])) {
		$wrapper->field_achatlog_receiver->set($params['to']);
	}
	$wrapper->field_achatlog_created->set(time());
	if (isset($params['data']['type']) && isset($params['data']['value'])) {
		$wrapper->field_achatlog_type->set($params['data']['type']);
		switch ($params['data']['type']) {
			case 'text':
				$wrapper->field_achatlog_text->set($params['data']['value']);
				break;
			case 'image':
			case 'video':
			case 'doc':
				$file = (array) $params['data']['value'];
				$items = array($file);
				$wrapper->field_achatlog_file->set($file);
				break;
		}
	}
	drupal_alter('achat_db_create_achatlog', $achatlog, $wrapper, $achat, $params);
	$wrapper->save();
}

/**
 * Implements hook_form_alter().
 */
function achat_db_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'achat_form' 
		&& isset($form_state['settings']['configure']['db']['history']) 
		&& $form_state['settings']['configure']['db']['history'] 
		&& isset($form_state['channel']) 
		&& $achat = achat_db_load_achat_by_channel($form_state['channel'])) {
		$output = '';
	  $query = new EntityFieldQuery();
	  $query->entityCondition('entity_type', 'centity')
	    ->entityCondition('bundle', 'achatlog')
	    ->fieldCondition('field_achat', 'target_id', $achat->cid)
	    ->fieldOrderBy('field_achatlog_created', 'value', 'ASC');
	  $result = $query->execute();
	  if (isset($result['centity'])) {
	  	$cids = array_keys($result['centity']);
	  	$centities = centity_load_multiple($cids);
	  	$output = achat_db_logs_render($centities, _achat_block_configure($form_state['block_type']));
	  }
	  $form['achat']['log'] = array(
	    '#markup' => '<div class="chat-log">' . $output . '</div>',
	  );
	}
}

/**
 * Render logs.
 *
 * @param $centities
 *
 * @param $configure
 */
function achat_db_logs_render($centities, $configure) {
	$output = '';
	foreach ($centities as $log) {
		$wrapper = entity_metadata_wrapper('centity', $log);
		$receivers_uid = array();
		foreach ($wrapper->field_achatlog_receiver->value() as $receiver) {
			$receivers_uid[] = $receiver->uid;
		}
		$data = array(
			'type' => $wrapper->field_achatlog_type->value(),
			'value' => $wrapper->field_achatlog_type->value() == 'text' ? $wrapper->field_achatlog_text->value() : (object) $wrapper->field_achatlog_file->value(),
		);
		$msg = _achat_msg_render($data, $configure);
		if ($msg && ($GLOBALS['user']->uid == $wrapper->field_achatlog_sender->uid->value() 
			|| $wrapper->field_achatlog_secret->value() == 0 
			|| in_array($GLOBALS['user']->uid, $receivers_uid))
		) {
			$author = '<span class="message-author">' . $wrapper->field_achatlog_sender->name->value() . ':</span>';
			$message = '<span class="message-text">' . $msg . '</span>';
			$time = '<span class="message-time">' . date('H:i', $wrapper->field_achatlog_created->value()) . '</span>';
			$output .= '<div class="achat-message"><div class="message-content"> ' 
							. $author . $message . '</div>' . $time . '</div>';
		}
	}
	return $output;
}